### PR TITLE
Changed conditions for handling view tensors in order to resolve test…

### PR DESCRIPTION
**Pull request by skotapati**
Changed how view tensors are handled in order to resolve test issue in nn.functional.bilinear

### CODE REVIEW

**Review by DenisVieriu97 — APPROVED** [review]
Looks good

**Comment by damian0815** [comment]
@DenisVieriu97 any word on this will be merged into mainline pytorch nightlies? is there a publicly-available roadmap?

**Comment by DenisVieriu97** [comment]
@damian0815 this is currently in PR at https://github.com/pytorch/pytorch/pull/94275. I will ping you once it gets in

**Comment by damian0815** [comment]
@DenisVieriu97 🙇 thank you!

**Comment by DenisVieriu97** [comment]
@damian0815 the PR got merged in. Please give a try and let me know if you still see any issues. Thanks!

**Pull request merged**
